import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/components/shared/Header/Header";
import Footer from "@/components/shared/Footer/Footer";
// import { Footer } from "@/components/shared/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       {/* <main>
         {children}
       </main> */}
        <header className="py-2 md:w-11/12 mx-auto max-w-screen-2xl">
          <Header></Header>
        </header>
       <main className="py-2  mx-auto min-h-[calc(100vh-302px)]">
         {children}
       </main>
        <footer className="py-2  mx-auto ">
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
